# Generated by Django 3.2 on 2022-02-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='city',
            field=models.CharField(default='', max_length=40),
        ),
    ]
