# Generated by Django 3.2 on 2022-02-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_orderlineitem_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='city',
        ),
    ]
