# Generated by Django 3.2 on 2022-02-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20220219_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colour',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='vintage',
            field=models.TextField(default='', null=True),
        ),
    ]
